# Generated by Django 3.2.3 on 2022-05-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosMedicos',
            fields=[
                ('id_producto_medico', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_producto_medico', models.CharField(max_length=50)),
                ('stock_producto_medico', models.IntegerField()),
            ],
        ),
    ]
